## Q1 JOIN
SELECT CPS.NAME_OF_SCHOOL, CPS.COMMUNITY_AREA_NAME, CPS.AVERAGE_STUDENT_ATTENDANCE, CSE.HARDSHIP_INDEX 
FROM chicago_public_schools AS CPS 
LEFT OUTER JOIN chicago_socioeconomic_data AS CSE 
ON CPS.COMMUNITY_AREA_NUMBER=CSE.COMMUNITY_AREA_NUMBER 
AND CSE.HARDSHIP_INDEX = 98

## Q2 JOIN

SELECT CC.CASE_NUMBER, CC.PRIMARY_TYPE, CSE.COMMUNITY_AREA_NAME
FROM chicago_crime AS CC 
LEFT OUTER JOIN chicago_socioeconomic_data AS CSE 
ON CC.COMMUNITY_AREA_NUMBER=CSE.COMMUNITY_AREA_NUMBER
AND CC.LOCATION_DESCRIPTION LIKE '%SCHOOL%'

##Q1 VIEW 

CREATE OR REPLACE VIEW CHIC_PUB_SCHOOLS AS
SELECT NAME_OF_SCHOOL AS SCHOOL_NAME, SAFETY_ICON AS SAFETY_RATING, FAMILY_INVOLVEMENT_ICON AS FAMILY_RATING, ENVIRONMENT_ICON AS ENVIRONMENT_RATING, INSTRUCTION_ICON AS INSTRUCTION_RATING, LEADERS_ICON AS LEADERS_RATING, TEACHERS_ICON AS TEACHERS_RATING
FROM chicago_public_schools;

SELECT * FROM CHIC_PUB_SCHOOLS

SELECT SCHOOL_NAME, LEADERS_RATING FROM CHIC_PUB_SCHOOLS

## Q12 STORED PROCEDURE

DELIMITER //

CREATE PROCEDURE UPDATE_LEADERS_SCORE(IN SCHOOL_ID INTEGER, IN LEADER_SCORE INTEGER)
BEGIN

FOR SCHOOL_ID = IN_SCHOOL_ID
	UPDATE chicago_socioeconomic_data
    SET LEADER_SCORE = IN_LEADER_SCORE

END //

DELIMITER;

#Q3 STORED PROCEDURE

